/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "e-commerce-api-on-stop-christmas-shop": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "e-commerce-api-one-stop-christmas-shop": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
